version: "3.8"

services:
  requestrecord:
    build: .
    command: python main.py
    ports:
      - 192.168.1.103:8001:12345
    volumes:
      - type: bind
        source: ./data
        target: /data